version: 2.1
orbs:
  architect: giantswarm/architect@4.35.6

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-etcd-cluster-migrator
          binary: etcd-cluster-migrator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build-etcd-cluster-migrator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push etcd-cluster-migrator chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "etcd-cluster-migrator"
          requires:
            - push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
